export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function EditorLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
