"use client";
import { ApolloProvider } from "@apollo/client";
import { initializeApollo } from "../lib/apolloClient";

type T = {
  children: React.ReactNode;
};

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: T) {
  const client = initializeApollo();
  return (
    <ApolloProvider client={client}>
      <html lang="ja">
        <body>{children}</body>
      </html>
    </ApolloProvider>
  );
}
