import { ApolloWrapper } from "../lib/apolloWrapper";

type T = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: T) {
  return (
    <ApolloWrapper>
      <html lang="ja">
        <body>{children}</body>
      </html>
    </ApolloWrapper>
  );
}
