import { ApolloWrapper } from "../lib/apolloWrapper";
import { Auth0ProviderWrapper } from "../lib/auth0ProviderWrapper";
import { UserProvider } from "@auth0/nextjs-auth0/client";

type T = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: T) {
  return (
    // <Auth0ProviderWrapper>

    <html lang="ja">
      <UserProvider>
        <ApolloWrapper>
          <body>{children}</body>
        </ApolloWrapper>
      </UserProvider>
    </html>

    // </Auth0ProviderWrapper>
  );
}
